// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float4> verticies;

struct VolumeOut
{
    float4 normal;
    float4 edgeNorm1;
    float4 edgeNorm2;
    float4 edgeNorm3;
};

RWStructuredBuffer<float4> Result;

[numthreads(8,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    //VolumeOut outV;

    float4 v1 = verticies[3*id.x + 0];
    float4 v2 = verticies[3*id.x + 1];
    float4 v3 = verticies[3*id.x + 2];

    //outV.normal = cross((v2-v1),(v3-v1));
    Result[id.x] = float4(1,1,1,1);
}
